In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.asarray(l)

array([1, 2, 3, 4])

In [4]:
a= [2,3,4]

In [6]:
np.asarray(a)

array([2, 3, 4])

In [7]:
b= np.matrix(l)

In [8]:
b

matrix([[1, 2, 3, 4]])

In [9]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [10]:
a = np.array(l)

In [11]:
a

array([1, 2, 3, 4])

In [12]:
c =a

In [13]:
c

array([1, 2, 3, 4])

In [15]:
c[0] =100

In [16]:
c

array([100,   2,   3,   4])

In [17]:
a

array([100,   2,   3,   4])

In [18]:
d = np.copy(a)

In [19]:
d

array([100,   2,   3,   4])

In [25]:
a[1] = 300

In [26]:
a

array([100, 300,   3,   4])

In [27]:
d

array([100, 400,   3,   4])

In [29]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
iterable = (i*i for i in range(5))

In [42]:
my_generator = (i*i for i in range(5))




In [43]:
my_generator


<generator object <genexpr> at 0x7fcb201c9690>

In [45]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [48]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [49]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

Numpy data type

In [50]:
l=[1,2,3,4,5]

In [5]:
ar = np.array(l)

In [53]:
ar.ndim

1

In [10]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [56]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [11]:
ar2.ndim

2

In [12]:
ar2.size

8

In [66]:
ar

array([1, 2, 3, 4, 5])

In [67]:
ar.shape

(5,)

In [68]:
ar2.shape

(2, 4)

In [70]:
ar.dtype

dtype('int64')

In [71]:
ar2.dtype

dtype('int64')

In [14]:
ar22 = np.array([(1.4,45,45),(23,45,56)])

In [15]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 56. ]])

In [16]:
ar22.dtype

dtype('float64')

In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [22]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [4]:
ar4 = np.zeros((3,4,2,3))

In [5]:
ar4.ndim

4

In [6]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
on = np.ones((2,3,2))

In [13]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [14]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [11]:
np.ones((2,4,3,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [17]:
np.empty((3,6))

array([[4.65636373e-310, 0.00000000e+000, 6.95062574e-310,
        6.95062684e-310, 6.95062682e-310, 6.95062574e-310],
       [6.95062573e-310, 6.95062572e-310, 6.95062573e-310,
        6.95062682e-310, 6.95062573e-310, 6.95062573e-310],
       [6.95062573e-310, 6.95062682e-310, 6.95062574e-310,
        6.95062574e-310, 6.95062660e-310, 6.95062684e-310]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [26]:
np.logspace(2,5 , 10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [30]:
arr = np.random.randn(3,4)

In [29]:
import pandas as pd

In [31]:
pd.DataFrame(arr)

0         1         2         3
0  0.171246 -0.541191  0.533540 -0.894965
1 -1.061698 -1.932656  0.836069  0.905650
2 -1.399337 -0.735162 -0.408509 -0.304588

In [32]:
np.random.rand(3,4)

array([[0.13428427, 0.70106188, 0.17062963, 0.74361191],
       [0.34477867, 0.81209931, 0.88558644, 0.75676536],
       [0.49152222, 0.61053371, 0.806644  , 0.75072402]])

In [35]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [36]:
arr = np.random.rand(3,4)

In [37]:
arr 

array([[0.61442423, 0.33803572, 0.0537544 , 0.36618622],
       [0.38311514, 0.95146109, 0.48367923, 0.16122253],
       [0.1490258 , 0.89607139, 0.49026261, 0.52048052]])

In [38]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [39]:
arr.reshape(6,-1)

array([[0.61442423, 0.33803572],
       [0.0537544 , 0.36618622],
       [0.38311514, 0.95146109],
       [0.48367923, 0.16122253],
       [0.1490258 , 0.89607139],
       [0.49026261, 0.52048052]])

In [42]:
arr1 = arr.reshape(6,-122334)

In [43]:
arr1

array([[0.61442423, 0.33803572],
       [0.0537544 , 0.36618622],
       [0.38311514, 0.95146109],
       [0.48367923, 0.16122253],
       [0.1490258 , 0.89607139],
       [0.49026261, 0.52048052]])

In [44]:
arr1[1][1]

0.3661862199628273

In [50]:
arr1[2:5,1]

array([0.95146109, 0.16122253, 0.89607139])

In [48]:
arr1[2:5]

array([[0.38311514, 0.95146109],
       [0.48367923, 0.16122253],
       [0.1490258 , 0.89607139]])

In [56]:
arr= np.random.randint(1,100 , (5,5))

In [57]:
arr>50

array([[ True,  True, False,  True,  True],
       [False,  True, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True, False,  True, False],
       [ True, False,  True,  True,  True]])

In [58]:
arr

array([[65, 74, 17, 94, 69],
       [19, 96,  7, 41, 26],
       [18, 57, 97, 99, 12],
       [ 3, 89,  8, 87, 48],
       [71, 12, 64, 84, 81]])

In [59]:
arr[2:4,[1,2]]

array([[57, 97],
       [89,  8]])

In [60]:
arr[0][0]

65

In [61]:
arr[0][0]= 5000

In [62]:
arr

array([[5000,   74,   17,   94,   69],
       [  19,   96,    7,   41,   26],
       [  18,   57,   97,   99,   12],
       [   3,   89,    8,   87,   48],
       [  71,   12,   64,   84,   81]])

In [64]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [65]:
arr1

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [66]:
arr2

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [67]:
arr1+arr2

array([[4, 3, 3],
       [2, 3, 3],
       [3, 4, 2]])

In [68]:
arr1-arr2

array([[ 0,  1,  1],
       [ 0, -1, -1],
       [ 1,  0,  0]])

In [69]:
arr1/arr2

array([[1. , 2. , 2. ],
       [1. , 0.5, 0.5],
       [2. , 1. , 1. ]])

In [70]:
arr1*arr2

array([[4, 2, 2],
       [1, 2, 2],
       [2, 4, 1]])

In [71]:
arr1@arr2

array([[ 8, 10,  8],
       [ 4,  5,  4],
       [ 7,  8,  7]])

In [72]:
arr1/0

/tmp/ipykernel_91/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [73]:
arr1+100

array([[102, 102, 102],
       [101, 101, 101],
       [102, 102, 101]])

In [74]:
arr1**2

array([[4, 4, 4],
       [1, 1, 1],
       [4, 4, 1]])

numpy Broadcasting

In [87]:
arr = np.zeros((4,4))

In [88]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
row = np.array([1,2,3,4])

In [82]:
row

array([1, 2, 3, 4])

In [90]:
row.ndim

1

In [91]:
row.shape

(4,)

In [89]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [92]:
row.T

array([1, 2, 3, 4])

In [93]:
col = np.array([[1,2,3,4]])

In [94]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [96]:
col.shape

(1, 4)

In [97]:
col.ndim

2

In [95]:
col

array([[1, 2, 3, 4]])

In [98]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [100]:
arr1 = np.random.randint(1,4,(3,4))

In [101]:
arr1

array([[3, 3, 2, 3],
       [1, 2, 2, 3],
       [1, 2, 2, 1]])

In [102]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.41421356, 1.        ]])

In [103]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [104]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.47712125],
       [0.        , 0.30103   , 0.30103   , 0.47712125],
       [0.        , 0.30103   , 0.30103   , 0.        ]])