In [1]:
import numpy as np

Numpy Array manipulation

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[5, 9, 9, 6],
       [5, 4, 3, 5],
       [2, 5, 1, 2]])

In [5]:
arr.reshape(2,6)

array([[5, 9, 9, 6, 5, 4],
       [3, 5, 2, 5, 1, 2]])

In [8]:
arr.reshape(2,-234)

array([[5, 9, 9, 6, 5, 4],
       [3, 5, 2, 5, 1, 2]])

In [9]:
arr.T

array([[5, 5, 2],
       [9, 4, 5],
       [9, 3, 1],
       [6, 5, 2]])

In [11]:
arr.flatten()

array([5, 9, 9, 6, 5, 4, 3, 5, 2, 5, 1, 2])

In [12]:
arr1 = np.array([1,2,3,4,5])

In [13]:
arr1.ndim

1

In [15]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 4, 5]])

In [17]:
arr

array([[5, 9, 9, 6],
       [5, 4, 3, 5],
       [2, 5, 1, 2]])

In [18]:
np.squeeze(arr)

array([[5, 9, 9, 6],
       [5, 4, 3, 5],
       [2, 5, 1, 2]])

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.squeeze(data)

array([1, 2, 3])

In [22]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [34]:
np.roll(arr1,1)

array([5, 1, 2, 3, 4])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Numpy Binary Operation

In [56]:
arr1 = np.random.randint(1,10,(3,4))

In [57]:
arr2 = np.random.randint(1,10,(3,4))

In [38]:
arr1

array([[1, 5, 5, 8],
       [8, 7, 8, 1],
       [9, 4, 7, 6]])

In [39]:
arr2

array([[2, 8, 2, 4],
       [5, 4, 3, 8],
       [6, 6, 8, 7]])

In [40]:
arr1+arr2

array([[ 3, 13,  7, 12],
       [13, 11, 11,  9],
       [15, 10, 15, 13]])

In [41]:
arr1-arr2

array([[-1, -3,  3,  4],
       [ 3,  3,  5, -7],
       [ 3, -2, -1, -1]])

In [42]:
arr1/arr2

array([[0.5       , 0.625     , 2.5       , 2.        ],
       [1.6       , 1.75      , 2.66666667, 0.125     ],
       [1.5       , 0.66666667, 0.875     , 0.85714286]])

In [43]:
arr1*arr2

array([[ 2, 40, 10, 32],
       [40, 28, 24,  8],
       [54, 24, 56, 42]])

In [44]:
arr1%arr2

array([[1, 5, 1, 0],
       [3, 3, 2, 1],
       [3, 4, 7, 6]])

In [45]:
arr1

array([[1, 5, 5, 8],
       [8, 7, 8, 1],
       [9, 4, 7, 6]])

In [46]:
arr2

array([[2, 8, 2, 4],
       [5, 4, 3, 8],
       [6, 6, 8, 7]])

In [49]:
arr1 ** arr2

array([[       4, 16777216,        4,      256],
       [    3125,      256,       27, 16777216],
       [   46656,    46656, 16777216,   823543]])

In [58]:
arr1 & arr2

array([[8, 0, 1, 4],
       [4, 0, 2, 4],
       [0, 1, 0, 4]])

In [59]:
~arr1

array([[ -9,  -9,  -2,  -7],
       [ -5,  -6,  -3,  -5],
       [ -9, -10,  -9,  -5]])

In [60]:
arr1|arr2

array([[ 8, 12,  3,  6],
       [ 4,  7,  7,  7],
       [13, 13, 14,  7]])

In [61]:
arr1>arr2

array([[False,  True, False,  True],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [62]:
arr2>arr1

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

Numpy String Operation

In [63]:
arr = np.array(['sudh','krish'])

In [64]:
arr

array(['sudh', 'krish'], dtype='<U5')

In [65]:
np.char.upper(arr)

array(['SUDH', 'KRISH'], dtype='<U5')

In [66]:
np.char.title(arr)

array(['Sudh', 'Krish'], dtype='<U5')

In [67]:
np.char.capitalize(arr)

array(['Sudh', 'Krish'], dtype='<U5')

Numpy Mathematical Functions

In [69]:
arr1

array([[8, 8, 1, 6],
       [4, 5, 2, 4],
       [8, 9, 8, 4]])

In [70]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825,  0.84147098, -0.2794155 ],
       [-0.7568025 , -0.95892427,  0.90929743, -0.7568025 ],
       [ 0.98935825,  0.41211849,  0.98935825, -0.7568025 ]])

In [71]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.54030231,  0.96017029],
       [-0.65364362,  0.28366219, -0.41614684, -0.65364362],
       [-0.14550003, -0.91113026, -0.14550003, -0.65364362]])

In [73]:
np.tan(arr1)

array([[-6.79971146, -6.79971146,  1.55740772, -0.29100619],
       [ 1.15782128, -3.38051501, -2.18503986,  1.15782128],
       [-6.79971146, -0.45231566, -6.79971146,  1.15782128]])

In [74]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.        , 0.77815125],
       [0.60205999, 0.69897   , 0.30103   , 0.60205999],
       [0.90308999, 0.95424251, 0.90308999, 0.60205999]])

In [75]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 2.71828183e+00, 4.03428793e+02],
       [5.45981500e+01, 1.48413159e+02, 7.38905610e+00, 5.45981500e+01],
       [2.98095799e+03, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01]])

In [76]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 1.        , 2.44948974],
       [2.        , 2.23606798, 1.41421356, 2.        ],
       [2.82842712, 3.        , 2.82842712, 2.        ]])

In [77]:
np.power(arr1,2)

array([[64, 64,  1, 36],
       [16, 25,  4, 16],
       [64, 81, 64, 16]])

In [78]:
np.mean(arr1)

5.583333333333333

In [80]:
np.median(arr1)

5.5

In [81]:
np.std(arr1)

2.5317429218272185

In [82]:
np.var(arr1)

6.409722222222222

In [83]:
np.min(arr1)

1

In [84]:
np.max(arr1)

9