Numpy Array Manipulation

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[9, 1, 4, 8],
       [8, 1, 9, 9],
       [1, 5, 9, 6]])

In [5]:
arr.reshape(6,2)

array([[9, 1],
       [4, 8],
       [8, 1],
       [9, 9],
       [1, 5],
       [9, 6]])

In [6]:
arr.reshape(2,6)

array([[9, 1, 4, 8, 8, 1],
       [9, 9, 1, 5, 9, 6]])

In [7]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [9]:
arr.reshape(4,3)

array([[9, 1, 4],
       [8, 8, 1],
       [9, 9, 1],
       [5, 9, 6]])

In [10]:
arr.reshape(7,1)

ValueError: cannot reshape array of size 12 into shape (7,1)

In [11]:
arr.reshape(2,-243)

array([[9, 1, 4, 8, 8, 1],
       [9, 9, 1, 5, 9, 6]])

In [12]:
arr.T

array([[9, 8, 1],
       [1, 1, 5],
       [4, 9, 9],
       [8, 9, 6]])

In [13]:
arr

array([[9, 1, 4, 8],
       [8, 1, 9, 9],
       [1, 5, 9, 6]])

In [14]:
arr.flatten()

array([9, 1, 4, 8, 8, 1, 9, 9, 1, 5, 9, 6])

In [15]:
arr1 = np.array([1,2,3,4,5])

In [16]:
arr1.ndim

1

In [17]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])